config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts
  resources :users, only: [:show]
  root 'posts#index'
  post 'restoration/:id' => 'posts#restoration'
  post '/posts/:id/done' => 'posts#done',   as: 'done'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
end

app/models/level_setting.rb
class LevelSetting < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    include Discard::Model
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
        validates :name, presence: true #追記
        validates :profile, length: { maximum: 200 } 
        has_many :posts,dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      # サインアップ時にnameのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      # アカウント編集の時にnameとprofileのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        render layout: false
    end
    def create
        post = Post.new(tweet_params)
        post.user_id = current_user.id
        post.save
        redirect_back(fallback_location: root_path)
    end
    def destroy
        post = Post.find(params[:id])
        post.discard
        redirect_back(fallback_location: root_path)
    end
    def done
        require "date"
        @today = Date.today #今日の日付
        post = Post.find(params[:id])
        post.update(done_at: @today ) #完了ボタンを押すとdone_atカラムに完了した日時を追加
        redirect_back(fallback_location: root_path)
    end
    def restoration
        require "date"
        @today = Date.today #今日の日付
        post = Post.find(params[:id])
        post.update(done_at:nil)
        redirect_back(fallback_location: root_path)
    end
    private
    def tweet_params
        params.require(:post).permit(:body, :time, :done_at)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        require "date"
        @today = Date.today
        @task =Post.new
        @user = User.find(params[:id])
        @tweets = @user.posts.where(done_at:nil).order(:time) 
        @tweets_done = @user.posts.where.not(done_at:nil) 

            @user_discarded_posts = @tweets_done
            @totalExp =  @user_discarded_posts.count
            @user.experience_point = @totalExp
            @user.save!
            levelSetting = LevelSetting.find_by(level: @user.level + 1);
            if levelSetting&.thresold.to_i <= @user.experience_point
                @user.level  += 1 if levelSetting
                @user.save!
            end
            # @user_undiscarded_posts = @user.posts.undiscarded
            # @totalExp =  @user_undiscarded_posts.count
            # @user.experience_point = @totalExp
            # @user.save!
            # levelSetting = LevelSetting.find_by(level: @user.level - 1);
            # if levelSetting&.thresold.to_i <= @user.experience_point
            # # &はlevelsettingがnilだったときに、nilとしてだす=>nilという文字をinteger型に変換する
            #     @user.level  -= 1 if levelSetting
            #     # levelSettingがtrueだった時に、上のコードが実行される。つまり、nilの時はfalseで0として変換されるので、上のコードは実行されない。
            #     @user.save!
            # end

    end
    protected
    def after_destroy_path_for(resource)
        redirect_to user_path(current_user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ミジンコ式GTD</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <h1>ミジンコ式GTD</h1>
      <div class="header-list">
        <ul>
          <%# <%= link_to '新規登録', new_user_registration_path %> %>
          <%= link_to 'ログイン', new_user_session_path %>
          <% if user_signed_in? %>
            <%= link_to "マイページへ", user_path(current_user.id) %>
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
          <% end %>
        </ul>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ミジンコ式GTD</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <body>
        <div class="parent">
            <div class="slider">
                <div class="slider-inner">
                    <%= image_tag 'top.jpg', class:'top' %>
                    <%= image_tag 'top2.jpg' ,class:'top' %>
                </div>
            </div>
            <div class="slider1">
                <div class="slider-inner1">
                    <%= image_tag 'top3.jpg', class:'top2' %>
                    <%= image_tag 'top4.jpg' ,class:'top2' %>
                </div>
            </div>
        </div>
        <footer>
          <h1 class="circle">ミジンコ式GTD</h1>
          <%= link_to '新規登録', new_user_registration_path, class:'touroku' %>
          <%= link_to 'ログイン', new_user_session_path, class:'touroku' %>
          <% if user_signed_in? %>
              <%= link_to "マイページへ", user_path(current_user.id) %>
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
          <% end %>
          <p>Copyright © GeekSalon All Rights Reserved.</p>
          <a href=“address_to@example.com”>メールはこちらへ</a>
        </footer>
      </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div><h5>レベル</h5>
    <% if @user.level>=6 %>
        <%= "Max" %>
    <% else  %>
        <%=  @user.level %>
    <% end %>
</div>
<% case  @user.level %>
    <% when 1 %>
        <%= image_tag "mizinko.jpeg", class: "image" %>
    <% when 2 %>
        <%= image_tag "boy.jpg", class: "image" %>
    <% when 3 %>
    <%= image_tag "sougakusei.png", class: "image" %>
    <% when 4 %>
    <%= image_tag "koukousei.png", class: "image" %>
    <% when 5 %>
    <%= image_tag "sarariman.png", class: "image" %>
    <% when 6 %>
    <%= image_tag "syacyou.jpeg", class: "image" %>
<% end %>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
    <%= link_to "編集する", edit_user_registration_path %>
<% end %>
<h2>進行中</h2>
<%= form_for @task do |f| %>
    <div class="field">
        <%= f.label :body %>
        <%= f.text_field :body, :size => 140 %>
        <%= f.label :締切 %>
        <%= f.date_field :time, :size => 140 %>
    </div>
    <%= f.submit "投稿する", class:'toukou' %>
<% end %>
<h2>進行中</h2>
<% @tweets.each do |t| %>
    <div class="tweet">
        <% if (t.time - @today).to_i > -1 %> 
            タスク名:<b><%= t.body %></b></br>
            締切:<%= t.time %></br>
            残り:<%= (t.time - @today).to_i %>日</br> 
            <%= button_to 'Done', done_path(t.id), method: :post %></br></br> 
        <% else %> #期限が切れているタスクの表示
            タスク名:<b><%= t.body %></b></br>
            締切:<%= t.time %></br>
            <%= (t.time - @today).to_i * -1 %>日期限が超過しています😀</br>
            <%= button_to 'Done', done_path(t.id), method: :post %></br></br>
        <% end %>
    </div>
<% end %>
<h1>完了済</h1>
<% @tweets_done.each do |t| %>
    <div class="tweet">
        タスク名:<b><%= t.body %></b></br>
        完了日:<%= t.done_at.strftime('%Y-%m-%d') %> </br></br>
        <%= button_to "復元", controller:"posts", action:"restoration", id:t.id, method: :post %>
         <%= button_to "削除", tweet_path(t.id), class:"botan" method: :delete %>
    </div>
    </p>
<% end %>
